dist: trusty
language: node_js
node_js:
- "10"
script:
- npm run coverage
after_success:
- npm run publish-coverage
branches:
  only: development
notifications:
  email:
    recipients:
    - 675375410@qq.com
    on_success: always        # default: change
    on_failure: never       # default: always
